name: Build Distribuition Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node-versions:
        required: true
        type: string

jobs:
  build:
    name: Build Distribuition on ${{ inputs.os }}
    if: >
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && (github.base_ref == 'main' || github.base_ref == 'dev'))
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node-versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.JS Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use Cache "node-modules"
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: node-modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-${{ matrix.node-version }}-

      - name: Use Cache "package-lock.json"
        uses: actions/cache@v4
        with:
          path: ./package-lock.json
          key: package-lock-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            package-lock-${{ runner.os }}-${{ matrix.node-version }}-

      - name: Build Distribuition
        run: |
          npm run build

      - name: Append -beta to package.json version
        if: >
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'dev')
        run: |
          # Get current version
          VERSION=$(node -p "require('./package.json').version")
          # Append -beta, e.g. 1.2.3-beta
          NEW_VERSION="${VERSION}-beta"
          echo "New version: $NEW_VERSION"
          # Update package.json version without creating a git tag
          npm version "$NEW_VERSION" --no-git-tag-version

      - name: Save package.json version
        run: |
          echo "PACKAGE_JSON_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Generate TAR package file & Checksum
        run: |
          npm run pack

      - name: Upload Checksum Artifact
        uses: actions/upload-artifact@v4
        with:
          name: checksum-${{ inputs.os }}-${{ matrix.node-version }}
          path: 'checksum.txt'

      - name: Upload TAR package file Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tar-package-file-${{ inputs.os }}-${{ matrix.node-version }}
          path: 'arch-unit-js.tar.tgz'
