name: Project Coverage Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node-versions:
        required: true
        type: string

jobs:
  publish:
    name: Coverage Package on ${{ inputs.os }}
    if: >
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && (github.base_ref == 'main' || github.base_ref == 'dev'))
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node-versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.JS Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Download Code Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Upload to Coveralls
        if: >
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main')
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: ./coverage/lcov.info
          parallel: true

      - name: Finish Upload to Coveralls
        if: >
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main')
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
