name: Merge into Main Workflow

on:
  pull_request:
    branches: ['main']
    types: ['closed']

jobs:
  install-ubuntu:
    uses: ./.github/workflows/install.yml
    with:
      os: ubuntu-latest
      node-versions: '["18.x", "20.x", "22.x"]'
  install-windows:
    uses: ./.github/workflows/install.yml
    with:
      os: windows-latest
      node-versions: '["18.x", "20.x", "22.x"]'
  # install-macos:
  #   uses: ./.github/workflows/install.yml
  #   with:
  #     os: macos-latest
  #     node-versions: '["18.x", "20.x", "22.x"]'

  test-ubuntu:
    uses: ./.github/workflows/test.yml
    with:
      os: ubuntu-latest
      node-versions: '["18.x", "20.x", "22.x"]'
    needs: install-ubuntu
  test-windows:
    uses: ./.github/workflows/test.yml
    with:
      os: windows-latest
      node-versions: '["18.x", "20.x", "22.x"]'
    needs: install-windows
  # test-macos:
  #   uses: ./.github/workflows/test.yml
  #   with:
  #     os: macos-latest
  #     node-versions: '["18.x", "20.x", "22.x"]'
  #   needs: install-macos
  build-ubuntu:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      node-versions: '["22.x"]'
    needs: [test-ubuntu, test-windows]

  publish-ubuntu:
    uses: ./.github/workflows/publish.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      os: ubuntu-latest
      node-versions: '["22.x"]'
    needs: [build-ubuntu]
