name: Publish Distribuition Workflow

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      os:
        required: true
        type: string
      node-versions:
        required: true
        type: string

jobs:
  publish:
    name: Publish Package on ${{ inputs.os }}
    if: >
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && (github.base_ref == 'main' || github.base_ref == 'dev'))
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node-versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.JS Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Download Checksum Artifact
        uses: actions/download-artifact@v4
        with:
          name: checksum-${{ inputs.os }}-${{ matrix.node-version }}
          path: .

      - name: Download TAR package file Artifact
        uses: actions/download-artifact@v4
        with:
          name: tar-package-file-${{ inputs.os }}-${{ matrix.node-version }}
          path: .

      - name: Validate TAR package file checksum
        run: sha256sum -c checksum.txt

      - name: Authenticate to npm
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Publish Package
        if: >
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.head_ref == 'dev' && github.base_ref == 'main')
        run: npm publish ./arch-unit-js.tar.tgz --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Package To Beta
        if: >
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'dev')
        run: npm publish ./arch-unit-js.tar.tgz --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
