name: Push & Merge into Dev Workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  install-ubuntu:
    uses: ./.github/workflows/install.yml
    with:
      os: ubuntu-latest
      node-versions: '["18.x", "20.x", "22.x"]'
  install-windows:
    uses: ./.github/workflows/install.yml
    with:
      os: windows-latest
      node-versions: '["18.x", "20.x", "22.x"]'
  # install-macos:
  #   uses: ./.github/workflows/install.yml
  #   with:
  #     os: macos-latest
  #     node-versions: '["18.x", "20.x", "22.x"]'
  
  test-ubuntu:
    uses: ./.github/workflows/test.yml
    with:
      os: ubuntu-latest
      node-versions: '["18.x", "20.x", "22.x"]'
    needs: install-ubuntu
  test-windows:
    uses: ./.github/workflows/test.yml
    with:
      os: windows-latest
      node-versions: '["18.x", "20.x", "22.x"]'
    needs: install-windows
  # test-macos:
  #   uses: ./.github/workflows/test.yml
  #   with:
  #     os: macos-latest
  #     node-versions: '["18.x", "20.x", "22.x"]'
  #   needs: install-macos
  build-ubuntu:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      node-versions: '["22.x"]'
    needs: [install-ubuntu, test-windows]
  
  publish-beta-ubuntu:
    - name: Publish Package To Beta
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [22.x]
      needs: [build-ubuntu]
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Setup Node.JS Environment
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            registry-url: 'https://registry.npmjs.org'

        - name: Use Cache "node-modules"
          uses: actions/cache@v4
          with:
            path: ./node_modules
            key: node-modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package.json') }}
            restore-keys: |
              node-modules-${{ runner.os }}-${{ matrix.node-version }}-

        - name: Use Cache "package-lock.json"
          uses: actions/cache@v4
          with:
            path: ./package-lock.json
            key: package-lock-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package.json') }}
            restore-keys: |
              package-lock-${{ runner.os }}-${{ matrix.node-version }}-

        - name: Use Cache "dist"
          uses: actions/cache@v4
          with:
            path: ./dist
            key: dist-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package.json') }}
            restore-keys: |
              dist-${{ runner.os }}-${{ matrix.node-version }}-

        - name: Download Package Artifact
          uses: actions/download-artifact@v4
          with:
            name: npm-package-${{ inputs.os }}-${{ matrix.node-version }}
            path: .

        - name: Download Checksum Artifact
          uses: actions/download-artifact@v4
          with:
            name: checksum-${{ inputs.os }}-${{ matrix.node-version }}
            path: .

        - name: Validate Package Checksum
          run: sha256sum -c checksum.txt

        - name: Publish Package To Beta
          run: npm publish --tag beta
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
