name: Push & Merge into Dev Workflow

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']
    types: ['closed']

jobs:
  install-ubuntu:
    uses: ./.github/workflows/install.yml
    with:
      os: ubuntu-latest
      node-versions: '["18.x", "20.x", "22.x"]'
  install-windows:
    uses: ./.github/workflows/install.yml
    with:
      os: windows-latest
      node-versions: '["18.x", "20.x", "22.x"]'

  lint-ubuntu:
    uses: ./.github/workflows/lint.yml
    with:
      os: ubuntu-latest
      node-versions: '["22.x"]'
    needs: [install-ubuntu]
  lint-windows:
    uses: ./.github/workflows/lint.yml
    with:
      os: windows-latest
      node-versions: '["22.x"]'
    needs: [install-windows]

  test-ubuntu:
    uses: ./.github/workflows/test.yml
    with:
      os: ubuntu-latest
      node-versions: '["18.x", "20.x", "22.x"]'
    needs: [lint-ubuntu]
  test-windows:
    uses: ./.github/workflows/test.yml
    with:
      os: windows-latest
      node-versions: '["18.x", "20.x", "22.x"]'
    needs: [lint-windows]

  build-ubuntu:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      node-versions: '["22.x"]'
    needs: [test-ubuntu, test-windows]

  publish-beta-ubuntu:
    uses: ./.github/workflows/publish.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      os: ubuntu-latest
      node-versions: '["22.x"]'
    needs: [build-ubuntu]
