name: Push & Merge into Dev Workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  install-ubuntu:
    uses: ./.github/workflows/install.yml
    with:
      os: ubuntu-latest
      node-versions: '["18.x", "20.x", "22.x"]'
  install-windows:
    uses: ./.github/workflows/install.yml
    with:
      os: windows-latest
      node-versions: '["18.x", "20.x", "22.x"]'
  # install-macos:
  #   uses: ./.github/workflows/install.yml
  #   with:
  #     os: macos-latest
  #     node-versions: '["18.x", "20.x", "22.x"]'
  
  test-ubuntu:
    uses: ./.github/workflows/test.yml
    with:
      os: ubuntu-latest
      node-versions: '["18.x", "20.x", "22.x"]'
    needs: install-ubuntu
  test-windows:
    uses: ./.github/workflows/test.yml
    with:
      os: windows-latest
      node-versions: '["18.x", "20.x", "22.x"]'
    needs: install-windows
  # test-macos:
  #   uses: ./.github/workflows/test.yml
  #   with:
  #     os: macos-latest
  #     node-versions: '["18.x", "20.x", "22.x"]'
  #   needs: install-macos
