name: Analyze Code Quality Workflow

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
    inputs:
      os:
        required: true
        type: string
      node-versions:
        required: true
        type: string

jobs:
  test:
    name: Analyze Code Quality on ${{ inputs.os }}
    if: >
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && (github.base_ref == 'main' || github.base_ref == 'dev'))
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node-versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.JS Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download Code Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: .

      - name: Download package.json version Artifact
        uses: actions/download-artifact@v4
        with:
          name: package-json-version
          path: .

      - name: Save package.json version to env variable
        run: |
          PACKAGE_JSON_VERSION=$(cat ./package-json-version.txt)
          echo "PACKAGE_JSON_VERSION=$PACKAGE_JSON_VERSION" >> $GITHUB_ENV

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.branch.name=${{ github.base_ref }}
            -Dsonar.projectVersion=${{ env.PACKAGE_JSON_VERSION }}
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Quality Gate Check
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
