name: Test & Lint Check Application Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node-versions:
        required: true
        type: string

jobs:
  test:
    name: Test Application on ${{ inputs.os }}
    if: >
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node-versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.JS Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use Cache "node-modules"
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: node-modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-${{ matrix.node-version }}-

      - name: Use Cache "package-lock.json"
        uses: actions/cache@v4
        with:
          path: ./package-lock.json
          key: package-lock-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            package-lock-${{ runner.os }}-${{ matrix.node-version }}-

      - name: Run Tests & Lint Check
        run: |
          npm run test
          npm run lint
          npm run format:check
